export const TIME_SLOTS = [
  { slot: "00:00" as const, isAvailable: true },
  { slot: "00:30" as const, isAvailable: true },
  { slot: "01:00" as const, isAvailable: true },
  { slot: "01:30" as const, isAvailable: false },
  { slot: "02:00" as const, isAvailable: true },
  { slot: "02:30" as const, isAvailable: false },
  { slot: "03:00" as const, isAvailable: false },
  { slot: "03:30" as const, isAvailable: true },
  { slot: "04:00" as const, isAvailable: false },
  { slot: "04:30" as const, isAvailable: true },
  { slot: "05:00" as const, isAvailable: true },
  { slot: "05:30" as const, isAvailable: false },
  { slot: "06:00" as const, isAvailable: true },
  { slot: "06:30" as const, isAvailable: false },
  { slot: "07:00" as const, isAvailable: true },
  { slot: "07:30" as const, isAvailable: false },
  { slot: "08:00" as const, isAvailable: false },
  { slot: "08:30" as const, isAvailable: true },
  { slot: "09:00" as const, isAvailable: true },
  { slot: "09:30" as const, isAvailable: true },
  { slot: "10:00" as const, isAvailable: true },
  { slot: "10:30" as const, isAvailable: true },
  { slot: "11:00" as const, isAvailable: true },
  { slot: "11:30" as const, isAvailable: true },
  { slot: "12:00" as const, isAvailable: true },
  { slot: "12:30" as const, isAvailable: true },
  { slot: "13:00" as const, isAvailable: true },
  { slot: "13:30" as const, isAvailable: true },
  { slot: "14:00" as const, isAvailable: true },
  { slot: "14:30" as const, isAvailable: true },
  { slot: "15:00" as const, isAvailable: true },
  { slot: "15:30" as const, isAvailable: true },
  { slot: "16:00" as const, isAvailable: true },
  { slot: "16:30" as const, isAvailable: true },
  { slot: "17:00" as const, isAvailable: true },
  { slot: "17:30" as const, isAvailable: true },
  { slot: "18:00" as const, isAvailable: true },
  { slot: "18:30" as const, isAvailable: true },
  { slot: "19:00" as const, isAvailable: true },
  { slot: "19:30" as const, isAvailable: true },
  { slot: "20:00" as const, isAvailable: true },
  { slot: "20:30" as const, isAvailable: true },
  { slot: "21:00" as const, isAvailable: true },
  { slot: "21:30" as const, isAvailable: true },
  { slot: "22:00" as const, isAvailable: true },
  { slot: "22:30" as const, isAvailable: true },
  { slot: "23:00" as const, isAvailable: true },
  { slot: "23:30" as const, isAvailable: true },
];

type TimeSlotInfo = (typeof TIME_SLOTS)[number];

// type TimeSlotsArray = TimeSlot[];

export type { TimeSlotInfo };
